#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# Example with runApplication:
# - runs blockMesh in background
# - redirecting standard output to log.blockMesh
# - does *not* run in log file already exists
Allclean
clear 
rm -rf log.*
runApplication blockMesh
runApplication surfaceFeatures 
runApplication snappyHexMesh -overwrite
runApplication checkMesh
#runApplication "$(getApplication)"


#------------------------------------------------------------------------------
